# Generated by Django 2.2.4 on 2023-01-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=500, verbose_name='keywords')),
                ('image', models.ImageField(upload_to='arts/', verbose_name='Art')),
                ('views', models.IntegerField(verbose_name='Views')),
            ],
            options={
                'verbose_name': 'Art',
                'verbose_name_plural': 'Arts',
            },
        ),
    ]
