# Generated by Django 2.2.4 on 2023-01-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_auto_20230120_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='saved',
            field=models.IntegerField(default=0, verbose_name='Saved'),
        ),
    ]
