# Generated by Django 2.2.4 on 2023-01-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
