# Generated by Django 2.2.4 on 2023-01-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230122_1204'),
        ('arts', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
