# Generated by Django 2.2.4 on 2023-01-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0007_comment_author_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_profile',
        ),
    ]
