# Generated by Django 2.2.4 on 2023-02-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0009_auto_20230122_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='gender',
            field=models.CharField(choices=[('girl', 'girl'), ('boy', 'boy')], default='girl', max_length=20, verbose_name='Gender'),
        ),
    ]
