# Generated by Django 2.2.4 on 2023-01-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(null=True, to='arts.Art'),
        ),
    ]
