# Generated by Django 2.2.4 on 2023-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230122_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/no-avatar.png', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
