# Generated by Django 2.2.4 on 2023-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../static/images/no-avatar.png', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
