# Generated by Django 2.2.4 on 2023-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230122_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recomendations',
            field=models.TextField(default=0, verbose_name='Recomendation keywords'),
            preserve_default=False,
        ),
    ]
