# Generated by Django 2.2.4 on 2023-02-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_recomendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='are_recomendations_are_ready',
            field=models.IntegerField(default=0, verbose_name='Are recomendations are ready?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recomendations',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendation keywords'),
        ),
    ]
