# Generated by Django 2.2.4 on 2023-02-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230202_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('girl', 'girl'), ('boy', 'boy')], default='girl', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recomendations',
            field=models.TextField(default='', verbose_name='Recomendation keywords'),
        ),
    ]
