# Generated by Django 2.2.4 on 2023-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='girl_or_boy',
            field=models.CharField(default='', max_length=200),
        ),
    ]
